### ISSUE TITLE
how run  this demp project ? 

### ISSUE THREAD

**Issue by CMingTseng** [ajavageek/renamer-compose#1]
Dear Sir

Thx your post 

https://blog.frankel.ch/state-jvm-desktop-frameworks/5/

i want run this demo project 

but  the mian.kt  lost   "snapshotFlow" !!

i upgrade the compose plugin to  version 0.3.2  &  kotlin version to  1.4.31

THX

**Comment by nfrankel** [comment]
This is a Gradle project: `./gradlew run` is all you need.
